### ISSUE TITLE
Requesting to become a short-term co-maintainer :)

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/nodequeue#1]
Hi @biolithic!

I am going to be working on a few sites that will be using nodequeue heavily, and I am happy to report and fix any issues that come up. Would you be interested in having me be a short-term maintainer, so that I could update, test, and possibly create a release for nodequeue? I know you are very busy at the moment and I don't want to trouble you with a bunch of PR reviews!

**Comment by biolithic** [comment]
Sure thing!  You can be co-maintainer and guide direction of this module  Thanks for getting sites into Backdrop.

**Comment by jenlampton** [comment]
Thank you :)
