### ISSUE TITLE
Doesn't display contextual links

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/nodequeue#10]
On *admin/structure/nodequeue/settings*, there is an option to "Display contextual links". (Help text: "A contextual link to edit the nodequeue will be displayed on Views that have a nodequeue relationship."

After creating a content view of posts with a nodequeue relationship in a Backdrop 1.6.3 site, I don't see any contextual link related to Nodequeue. (I created a page and a block view, and tested "Show content" and "Show fields". On the views page and the views block, I had a look at the contextual links of the view itself and at the ones of the single posts, but still no Nodequeue link.)

**Comment by jenlampton** [comment]
Ah yes, I was checking the wrong config value name. Fix coming soon :)

**Comment by olafgrabienski** [comment]
Thanks for fixing the contextual links! I can see (and use) them in a views block after the update to Nodequeue 1.x-2.1.2.
