### ISSUE TITLE
Error when configuring roles for a nodequeue

### ISSUE THREAD

**Issue by jackaponte** [backdrop-contrib/nodequeue#16]
When trying to edit a nodequeue to allow the Staff role on my site to manipulate a nodequeue, I received an error screen ("The website encountered an unexpected error. Please try again later.")

This error appeared in the logs:

`PDOException: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: 'staff' for column 'rid' at row 1: INSERT INTO {nodequeue_roles} (qid, rid) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1); Array ( [:db_insert_placeholder_0] => 1 [:db_insert_placeholder_1] => staff ) in nodequeue_save() (line 1079 of /var/www/test/alp/modules/contrib/nodequeue/nodequeue.module).`

It seems like Nodequeue is trying to save the value "staff" to an integer-only column, `rid`. My current workaround: in general site permissions gave staff role the "manipulate all queues" permission.

I'll do my best to test any patches in a timely manner, though I tend to be not so great at that these days!

**Comment by jenlampton** [comment]
I've pushed a fix for this -- along with an update hook. It will be included in the next release.
