### ISSUE TITLE
deleting simple nodequeue not deleting view

### ISSUE THREAD

**Issue by b1daly** [backdrop-contrib/nodequeue#20]
Deleting a nodequeue leaves the view it created, without being able to delete view directly. It is resulting in "ghost view" piling up, that are disabled. If anyone knows a work around, that would be swell...

**Comment by jenlampton** [comment]
Thanks for the issue @b1daly! I have addressed this problem in https://github.com/backdrop-contrib/nodequeue/issues/9 also.
