### ISSUE TITLE
auto created view not linked to nodequeue under "relationship" parameter

### ISSUE THREAD

**Issue by b1daly** [backdrop-contrib/nodequeue#21]
the auto created view doesn't show anything, until I linked it with the specific view under the relationships section...it seems like it should automatically set this parameter

**Comment by b1daly** [comment]
the behavior I'm seeing: the node is created, and under the 'RELATIONSHIPS' section is listed 'Nodequeue: Queue' , have to click this link, and in next page there is a checkbox to enable the particular queue

**Comment by jenlampton** [comment]
Thanks for the bug report @b1daly, I have addressed a fix for this in https://github.com/backdrop-contrib/nodequeue/issues/9, since it was reported there as well.
