### ISSUE TITLE
getting error messages on manage subqueue page

### ISSUE THREAD

**Issue by b1daly** [backdrop-contrib/nodequeue#22]
every time I open a 'manage subqueue' page I get the following message:

Notice: Trying to get property of non-object in nodequeue_admin_view_title() (line 782 of /app/backdrop/modules/nodequeue/nodequeue.admin.inc).

the same message gets added every time I visit page, stacking up! not sure if this is bug, but UX is poor, as there is no apparent way to delete the red error messages

**Comment by olafgrabienski** [comment]
I can confirm the issue: I also get the "Notice: Trying to get property of non-object (...)" message in the DBlog when I visit a *Manage subqueue* page.

> the same message gets added every time I visit page, stacking up! not sure if this is bug, but UX is poor, as there is no apparent way to delete the red error messages

@b1daly If I understand you correctly, you can disable the error messages which are directly displayed on the configuration page: Go to `admin/config/development/logging` and set the "Error messages to display" option to "None". (Which is the recommended setting for production sites.)

**Comment by bradbulger** [comment]
The change from #12 is causing this, it removed the `is_object($subqueue)` test before the reference to `$subqueue->sqid`. I don't understand why. It seems like maybe the "MANAGE QUEUE" link should be sending the user to /admin/structure/nodequeue/N instead of /admin/structure/nodequeue/N/view/N for simple nodequeues in any case.

**Comment by jenlampton** [comment]
Yeah, I'm not sure now why I thought that change would fix the php notice. Reverting the change and reopening that issue.

**Comment by jenlampton** [comment]
I'm not seeing `Notice: Trying to get property of non-object in nodequeue_admin_view_title` anymore after reverting that change, so going to call this fixed. (Please re-open the issue if that's not the case)
