### ISSUE TITLE
Move nodequeues from database to config

### ISSUE THREAD

**Issue by Al-Rozhkov** [backdrop-contrib/nodequeue#3]
Is it a good idea to store nodequeues and appropriate settings in config?

**Comment by jenlampton** [comment]
If the nodequeues contain node IDs, those should remain in the database as the node IDs will be different, and won't be deployable along with the rest of config.  Settings for the queues, however, should be in config.

**Comment by Al-Rozhkov** [comment]
Thanks for the explanation @jenlampton.
