### ISSUE TITLE
JS error "Duplicate position value." when adding new items to the queue

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/nodequeue#34]
When adding the 3rd or later items to a queue (the first and second item are fine, for some reason) I see the error `Duplicate position value.` at the top of the page, and the item is not added to the queue.  Additionally, the placeholder value for the  `Add to queue` form becomes the node title and node ID for the item that would not add properly.

When I hit the "Show row weights" link at the top right to reveal the position values, I can see that both positions were set to `1`.  

If I adjust the position for the second item to `2` and save the form, the form saves properly, but when the page reloads the second position field again reads `1`.

**Comment by jenlampton** [comment]
Pushed a fix for this bug. Closing issue.

**Comment by jackaponte** [comment]
Thanks for the fix, Jen! Since there's not been a new release I created [this patch file for Nodequeue,](https://gist.github.com/jackaponte/6485fbc5de1780b8caedf89884666b94) sharing in case it's helpful to anyone else!

**Comment by jenlampton** [comment]
Sounds like it's time for a new release :)
