### ISSUE TITLE
Deprecated function create_function()

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/nodequeue#36]
Get this error:

> Deprecated function: Function create_function() is deprecated in nodequeue_save_subqueue_order() (line 1156 of /app/modules/contrib/nodequeue/nodequeue.admin.inc).

https://www.php.net/manual/en/function.create-function.php

**Comment by herbdool** [comment]
@jenlampton I've got a PR that fixes this

**Comment by jenlampton** [comment]
Looks great, thanks @herbdool !
