### ISSUE TITLE
Tab "Queue" doesn't show up

### ISSUE THREAD

**Issue by Al-Rozhkov** [backdrop-contrib/nodequeue#4]
Menu tab for adding node to Nodequeue always hidden, even with "Create a menu tab" settings enabled.

**Comment by Al-Rozhkov** [comment]
Simple PR: https://github.com/backdrop-contrib/nodequeue/pull/5

**Comment by Al-Rozhkov** [comment]
BTW I'll be greatful for any advices about creating pull requests. Please tell me if I did something wrong, because I'm doing my first steps at this :)

**Comment by Al-Rozhkov** [comment]
Sorry for mentioning you here @jenlampton, but we don't have maintainer for this project and you are last maintainer who made commit in this repo. Also you are experienced developer who can review my PR and give me permission to merge it.

I stick to the rule: You will not push changes to a repository for which you are not a current maintainer.

**Comment by jenlampton** [comment]
Hi @Al-Rozhkov and thank you for the PR! The mention is perfectly warranted, as I am the current maintainer, though it looks like I forgot to update the readme :/  Sorry about that.

**Comment by jenlampton** [comment]
Your PR looks great, nice work. I've merged it and it will be in the next release of the module.

**Comment by jenlampton** [comment]
There's a new release now containing this fix :)

**Comment by jenlampton** [comment]
Doh, did I do it wrong?

**Comment by Al-Rozhkov** [comment]
![empty-tab](https://cloud.githubusercontent.com/assets/16973264/24979769/839fdc8e-1fe6-11e7-9032-367290b36f8c.jpg)

Something go wrong. This tab is empty now.

**Comment by jenlampton** [comment]
Yep, something got lost...  pushing back up now...

**Comment by jenlampton** [comment]
okay, can you try it again now? https://github.com/backdrop-contrib/nodequeue/releases/tag/1.x-2.1.1

**Comment by Al-Rozhkov** [comment]
Yes! It works :)

**Comment by jenlampton** [comment]
Yay!  thank you :)
